### PR TITLE
Include built files in repo for bower.

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
So that I'm clear, all.fineupload.js contains S3, Azure, and Traditional file uploads?

**Comment by mrjoelkemp** [comment]
Yes, that's the case. 2/3 uploader types used on the network isn't bad. It's a few hundred lines of unnecessary code, which isn't terrible.

Can we add a card to also dump a minified version in here to avoid minifying all 16k lines on every build?

**Comment by mrjoelkemp** [comment]
:+1:

**Comment by rnicholus** [comment]
It also contains all the code needed to generate S3 signatures entirely client-side, something you will only need if you are using Fine Uploader S3's serverless-uploads feature (literally only a server that serves up your JS and HTML files, nothing else). If you're not using this (it's uncommon in my estimation), that's another 1k lines of code.

**Comment by mikesherov** [comment]
@mrjoelkemp avoiding adding the min files to the dist because then we have to explicitly exclude it from the network in our uglification step, and we won't have an unminified version during dev, and it just didn't seem like it was worth the effort to avoid the few milliseconds it takes to minify the thing.

The only reason I did that with jquery was because it was hard to write the uglification exclusion for jquery, so I just avoid uglifying the whole thing.

**Comment by mrjoelkemp** [comment]
@rnicholus Thanks for the details :)

@mikesherov The problem you're hinting at could potentially be achieved with a custom requirejs plugin that checks for a production environment and resolves to a full or minified version of the file. We could use `has('built')` to signal the environment. You'd signal for an environment-based dependency like `env!vendor/all.fine-uploader`.

We can chat more about this elsewhere. This isn't a blocker.

**Pull request merged**
